server:
  port: 9999
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9999/eureka

spring:
  application:
    name: eurake-server